### ISSUE TITLE
Improve dummy data when loading mastodon project without image data

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#206]
## User Story

Users often transfer only *.mastodon files without the image data. This is done for practical reasons, as the image files might be very large and are therefore hard to share. A user would like to be able to open *.mastodon files without the actual image data available. This is currently quite complicated and should be improved.

### Current complicated user interaction:
1. User opens a *.mastodon file without image data present.
2. A dialog pops up to tell the user that dummy data is loaded instead:
![image](https://user-images.githubusercontent.com/24407711/201314798-6175f313-ca43-4af2-be73-3eab371a5788.png)
3. The dummy data always has only a fixed number of timepoints. This means the TrackScheme only displays a part of the data and is therefore not usable:
![image](https://user-images.githubusercontent.com/24407711/201315696-2df60311-41a7-47db-9b5d-9ceb9c264ad6.png)
4. The BigDataViewer (BDV) is in similar way barely functional:
![image](https://user-images.githubusercontent.com/24407711/201320019-4b8c9d0a-1f67-41dc-a348-b64a26252904.png)
5. In order to fix this problem the user needs to follow the instructions of dialog in step (2): Go to "File -> Fix Image Path..." this dialog is part of another git project "mastodon-tomancak", and might sometime not be installed. It allows users to semi-automatically enter pixel sizes and image sizes. Finally the "image path" in the project file is replaced by a dummy string.
6. Mastodon needs to be closed an the project needs to be reopened.

### Ideal user interaction:
1. User opens a *.mastodon file without image data present.
2. A dialog pops up to tell the user that dummy data is loaded.
3. Mastodon opens the project with dummy data, that has appropriate size and time points, to use TrackScheme and BDV.
4. _(Ideally the dummy data also has the same pixel size & image size & transformation as the original data, so that plugins relying on this information work as expected.)_

## Acceptance criteria

1. Mastodon Plugin saves a copy of the SpimDataFile directly into the mastodon project.
1. When opening a Mastodon project, it is checked, if the actual/original SpimDataFile is available. If it is not available the copy of the SpimDataFile within the Mastodon project is read.
1. In that case the user is informed, that no image data is available, but that lineage data can still be analysed. Relevant parameters, such as pixel size, image size are read from the copy of the SpimDataFile
1. Generate appropriate Dummy data, i.e. black background with appropriate size and appropriate number of time segments

## Tasks
- [x] Save SpimDataFile to the Mastodon project, when a Mastodon project is saved. Suggested file name: "dataset.xml.backup"
- [x] When opening a Mastodon project and no SpimDataFile is available, try to read "dataset.xml.backup" from Mastodon project file
- [x] Show a dialog informing the user: "No image available. Relevant meta information was read from Mastodon project file. You will be able to work with the lineage data. Do you want to procced?" "Yes/No"
- [x] In the "Yes" case, the image sizes, pixel sizes, and image transform parameters are read from the "dataset.xml.backup" file.  Instead of the intensity image, a black dummy image is loaded that has the same pixel transformation as the original image. _This results in reading the dataset.xml without the *.tif or *.h5 files present. To do so, it is probably necessary to replace the standard image loaders with dummy image loaders, this might require changes to the BDV libraries._
- [x] Path of SpimDataFile remains the same the same and is not updated.

## Additional Information

- Path if SpimDataFile stored in project file
![grafik](https://user-images.githubusercontent.com/10515534/200807549-0fe4ae4a-78d5-4237-80fc-66c5af06b5f3.png)

- Example content of a SpimDataFile

![grafik](https://user-images.githubusercontent.com/10515534/200807702-38c44387-8e6b-4215-8264-c55cbf44ded9.png)

- Documention of Discussion Matthias-Stefan:

![20221109_110507](https://user-images.githubusercontent.com/10515534/200813899-bda2e3dd-483c-458e-8a1b-f384debf8559.jpg)

**Comment by stefanhahmann** [comment]
Resolved by https://github.com/mastodon-sc/mastodon/pull/210
