### ISSUE TITLE
Reduce number of points to be drawn in Grapher

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#219]
# User Story

When using the Grapher, the navigation gets very slow in situations where many points are drawn.

![grafik](https://user-images.githubusercontent.com/10515534/205890779-d7dc1adc-0232-4ea5-98ce-11fcf895251c.png)

Also, in these situations it is difficult to actually visually analyse the plotted data, since to much points lie on top of each other.

It would be good, if there was some level of detail, e.g. as it is common in maps:

![grafik](https://user-images.githubusercontent.com/10515534/205891397-c7976d96-8c48-448c-a464-19b97956553a.png)

# Acceptance criteria

1. Point reduction algorithm does increase UI performance of the grapher (and not decrease it by too complex algorithms)
1. It should be possible for the user to find out, how much points are not drawn due to the level of detail

# Task
- [ ] Find suitable point reduction algorithm for the grapher
  - [ ] Try DBSCAN
- [ ] Find settings for this algorithms that work good in different scenarios
- [ ] Draw representation for the reduced points (e.g. 5k... points) here

# To be discussed:
- [ ] How to deal with drawing the edges in these case?

**Comment by tinevez** [comment]
Hello @stefanhahmann 
I would like to close this issue - at least temporarily - in the light of our recent discussion.

Indeed, a grapher that could harness rendering a `full graph` context with more than millions of points require some implementation `Level of Details` (LOD), as you pointed out above. 

I actually starting working on it last year, trying to come up with an octree implementation for the rendering, or something based on the existing kd-tree. I was not happy with the results of the prototype, which exists on a branch. It looks cheap. It probably should redone properly.

But recently, I was reading a paper about a tool and discussing with its author: https://tissuumaps.github.io/
They display a large number of 2D points on an interactive canvas as well. 
For version 2 they used the level of details, but for version 3, as stated in the paper about it (https://www.sciencedirect.com/science/article/pii/S2405844023025136) they switched to a rendering engine based on OpenGL and simply gave up on the LOD. The main author told me that OpenGL could harness their thousands of million points without the need for that.

So I started working on an OpenGL grapher, which is here:
https://github.com/mastodon-sc/mastodon-grapher-opengl

For now, it has fewer features that its non opengl counterpart, but should address the issue you mention. I suggest to reopen it if we are not satisfied with the first version of the opengl grapher.

**Comment by stefanhahmann** [comment]
I agree. Let's try the opengl first.

**Comment by stefanhahmann** [comment]
Just made a comparison on a large dataset (~200.000 Spots). Rendering in the existing Grapher took ~800ms on my machine. Rendering in the OpenGL Grapher took 1-2ms on my machine.
