### ISSUE TITLE
Allow free form selection in Grapher Window

### ISSUE THREAD

**Issue by stefanhahmann** [mastodon-sc/mastodon#220]
# User Story

It would be good if data points in the grapher window could be selected not only using rectangular selection, but also via free form selection, similar to Napari plotter.

Selection in the Grapher window using rectangular selection: 

![GIF 06 12 2022 12-10-54](https://user-images.githubusercontent.com/10515534/205896615-2d88758f-ffe9-4543-8b91-706b1db0354d.gif)

Napari Cluster Plotter:

![multi-select-manual-clustering](https://user-images.githubusercontent.com/10515534/205898334-f7f7d7ec-01b7-4e72-b104-623ec22a20fe.gif)

# Acceptance criteria
1. Possibility to change selection in UI (either via Click-Button in the UI or by some Key pressed + Mouse dragging combination)
1. Free form is drawn in the Grapher
1. One free form is possible simultaneously (as only one simultaneous selection is possible at the moment)
1. Points in the Grapher are selected according to the free form - similar to rectangular selection
1. Free form is deleted and selection is deleted if a new selection is started.

# Tasks
*  [x] Implementation of UI handling to draw free form
*  [x] Draw free form in Grapher
*  [x] Select points according to free form
*  [x] Delete free form and selection, if a new selection is started.
