### ISSUE TITLE
Git Compatible Mastodon Storage Format

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon#290]
This is a part of: mastodon-sc/mastodon-tomancak#15

Currently Mastodon provides two storage formats. As folder or as *.mastodon. Both file formats might have their problems when used inside a git repository:
1. **When text files are used:** Git merge might introduce inconsistencies in the text files, when merge two changes to the same dataset. Conflicting changes, like removing a spot & adding a edge two the spot. Might not appear as conflicting changes.
2. **When binary files are used:** Commit many different version of a large binary file might blow up the repository size and and a size limitation in git or GitHub might ruin the attempts to version Mastodon files.

## Possible solutions:
* ~Text based~
* Or binary files divided into blocks (preferred)
  * Make sure to always change one small file, whenever there is a change to the mastodon project. This will cause a git merge conflicts, and prevent git from destroying the dataset during merge attempts, i.e. no automatic merge will be done by git.

### Binary files divided into blocks

**Introduce a key** Mastodon rewrites the spot ids when saving a projects. Non constant spot ids are problematic. A small change in the ModelGraph can easily change a large number of spot ids. This is a problem for efficient storage (delta compression) of multiple versions with git. It is therefor necessary to have a key value that normally doesn't change.

The data in a mastodon project could be expressed in two tables
```
spot table:
------------
1. spot-key (unique and constant)
2. timepoint
3. x
4. y
5. z
6. label
7. covariance matrix
?? is there more

link table
-----------
1. link-key (unique and constant)
2. source spot-key
3. target spot-key
4. outgoing edge index
5. incoming edge index
```
Additionally, tables for properties should be created. These cover tagsets and features
```
property tables:
------------
1. spot-key or link-key (spot vs link can currently be derived from the filename)
2. value (e.g. feature value, tag value as boolean)
```

These tables could be stored in a **simple chunked binary format** (easiest solution using DataOutputStream, which would Java-specific) or as **ZARR tables** (could potentially be read also using Python scripts). A table should be sorted by the key and be chunked. For example keys 0-1000 are written into the first file, keys 1000-2000 are written into the second file etc.

**Using UUID as key value** 
* advantage:
  *  avoiding clashes.
* disadvantages:
  *  unevenly distributed
  *  not dense waste memory
  *  Data would need to be stored in kind of a chunked hash table. Which is pretty complicated. Unsolved question: which UUID entry would be stored in which chunk?

**Possible alternative to UUID** use a simple counter (integer or long). Each new spot receives an id from this counter. When spots are deleted this id will never be assigned again. **(preferred)**
* advantages:
  * less memory required
  * quicker iteration
  * may potentially used as indices for arrays (having "wholes")
* disadvantage:
  * clashes may occur when merging edits from two users. the merge tool would need to resolve this and assign new unused ids 

If spots are deleted, "wholes" are not filled. Spots need subsequently to be removed from link-tables, tag-tables and feature tables. 

### Text format using UUID (not-preferred)

Each spot and link gets a UUID. The spot table and link tables are stored in text files with rows:
```
spot table
--------
spot_UUID,timepoint,x,y,z,label,covariance matrix

link table
--------
link_UUID, source_spot_UUID, target_spot_UUID, outgoing_edge_index, incomming_edge_index
```
The text format has the advantages:
* git diff would do a proper job out of the box
* git blame would work as expected

and disadvantages:
* git merge would cause false positive conflicts, and more critically false negative conflicts.

It's probably still necessary to divide the text file into chunks in order to save memory when using git.

## TODOs:

- [x] Decide, if ZARR can be used to store the tables. Check if Strings can be stored in ZARR tables.
- [x] Decide, if UUID should be as key or simple counter
- [ ] Implement spot key as a feature of data type long
- [ ] Implement Serializer/Deserializer for MASGITO format
  - [ ] Divide into chunks, e.g. 1.000 rows per chunk
  - [ ] Write/Read chunks
  - [ ] Write/Read Spot key feature max value
- [ ] UI
  - [ ] Save to collaborative compatible format
  - [ ] Read from collaborative compatible format
